### ISSUE TITLE
在NodeJS中使用时提示：XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by Heart-King** [bmob/hydrogen-js-sdk#28]
ReferenceError: XMLHttpRequest is not defined
    at D:\NodeJS\BookSpider\node_modules\hydrogen-js-sdk\src\lib\axios.min.js:9:2483
    at new Promise (<anonymous>)
    at e.exports (D:\NodeJS\BookSpider\node_modules\hydrogen-js-sdk\src\lib\axios.min.js:9:2384)
    at e.exports (D:\NodeJS\BookSpider\node_modules\hydrogen-js-sdk\src\lib\axios.min.js:9:8385)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

**Comment by chenby** [comment]
`const axios = require('./axios.min')`
作者把h5引入的axios和nodejs引入的axios搞错了，具体参考
https://stackoverflow.com/questions/38453307/axios-with-node-js-referenceerror-xmlhttprequest-is-not-defined

**Comment by Heart-King** [comment]
感谢热心回答，找到原因了，因为Bmob的版本有好几个，下载时搞混了，没太注意。因为用的是另外一个版本的SDK才导致出的问题，用这个版本是没有问题的。
